name: code coverage workflow using sonarqube
on: push
jobs:
  job_sonar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code on the runner vm.
        uses: actions/checkout@v7
      - name: install java
        uses: actions/setup-java@v7
        with:
          java-version: '17'
          distribution: 'temurin'  
      - name: code coverage using sonarqube
        run: mvn sonar:sonar -Dsonar.projectKey=sridharharika_sridharharika-sonarqube -Dsonar.host.url=https://sonarcloud.io -dsonar.organization=sridharharika -Dsonar.token=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           
